apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-ms
  template:
    metadata:
      labels:
        app: users-ms
    spec:
      containers:
      - image: alfred0823/users:latest
        name: users
        ports:
        - containerPort: 8001
