apiVersion: v1
kind: Service
metadata:
  name: mysql8
spec:
  ports:
    ## puerto del servicio para el trafico
  - port: 3306
    protocol: TCP
    ## puerto interno del contenedor
    targetPort: 3306
  selector:
    app: mysql8
  type: ClusterIP
